Список заметок и создание/редактирование
Grehhov/notes pull request #1
Opened 2019-03-15 11:15 UTC by Grehhov

2019-03-15 12:33 UTC, lenant requested changes

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        RecyclerView recyclerViewNotes = (RecyclerView)findViewById(R.id.notes);
После даункаста `(RecyclerView)` должен быть пробел. Но на самом деле, тут не должно быть самого даункаста - раньше он был необходим, но сейчас `findViewById` скастит само.

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        FloatingActionButton createNoteFab = (FloatingActionButton)findViewById(R.id.create_note_fab);
Даункаст не нужен (кстати, студия рисует кастинг серым - это означает какие-то ненужные действия)

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +    public static final int CREATE_NOTE_REQUEST = 1;
Константы должны идти над полями.

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +    List<Note> notes = new ArrayList<>();
private

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +    List<Note> notes = new ArrayList<>();
Следующее поле и константа CREATE_NOTE_REQUEST тоже

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        Bundle bundle = data.getExtras();
`data.getExtras()` тоже может быть null, поэтом в след строчке возможен креш (студия кстати это подсвечивает), так что проверь bundle на null тоже.

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        if ("".equals(bundle.getString("name"))) {
`"name"` и остальные ключи нужно вынести в именованные константы. Если ключа нет в bundle, то результат будет null, а не пустая строка. Лучше всего проверять так: 
`TextUtils.isEmpty(bundle.getString("name"))` - это проверит и на null, и на пустую строку.

Кроме того, `bundle.getString("name")` у тебя встречается более одного раза в коде - поэтому нужно вынести ее результат в переменную. Студия тут может помочь сделать это быстрее: в конце выражения `bundle.getString("name")` напиши `.var`, студия подскажет вариант сделать переменную, жмешь энтер и студия вынесет в переменную результат тут и в остальных местах в этом методе где есть это выражение.

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteActivity.java
> +            public void onClick(@NonNull View view) {
Вынеси содержимое метода в отдельный метод, чтобы onCreate было проще читать.

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteActivity.java
> +                String name = ((TextView)findViewById(R.id.name_edit_text)).getText().toString();
даункаст не нужен

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteActivity.java
> +                bundle.putString("name", name);
используй именованные константы из MainActivity

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteActivity.java
> +            String name = receivedBundle.getString("name");
используй именованные константы из MainActivity

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +            nameView = (TextView) itemView.findViewById(R.id.name);
каст не нужен

2019-03-15 12:33 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +                Context context = view.getContext();
Стоит вынести содержимое этого метода в MainActivity. Идея такая: адаптер отвечает только за логику с view holders, а что делать при нажатии на элементы, типа открывать другой экран, он знать не должен. 

Чтобы позвать метод активити из адаптера, можно передать в адаптер активити и явно вызвать у него метод. Но этот метод плох: так ты завяжешься на конкретный активити и адаптер нельзя будет использовать с другим активити. Поэтом правильно сделать так: создай в адаптере внутренний интерфейс, который будет имплементить активити. Внутрь адаптера передавай активити, но теперь уже как интерфейс. Вызывай метод `onItemClick(Note note)`, который будет в интерфейсе, а его реализация в активити сделает то, что у тебя делается тут.

2019-03-15 12:33 UTC, lenant commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/notes"
Называй id всегда как `название файл минус activty/fragment/view_суть`
Например, тут main_notes. Но лучше main_notes_recycler.

2019-03-15 12:33 UTC, lenant commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/create_note_fab"
main_create_note_fab

2019-03-15 12:33 UTC, lenant commented on app/src/main/res/layout/activity_note.xml
> +        android:id="@+id/name_edit_text"
note_name_edit_text, остальные id тоже переименуй плиз

2019-03-15 12:33 UTC, lenant commented on app/src/main/res/layout/activity_note.xml
> +        android:text="Название:"/>
Все строки должны быть размещены в strings.xml. Правила именования строк примерно как именования id-шников, но не такие строгие, так как строчка может быть одна использована в разных местах (id тоже, но это более редкий кейс).

2019-03-18 06:15 UTC, Grehhov commented on app/src/main/java/com/example/notes/NoteActivity.java
> +                String name = ((TextView)findViewById(R.id.name_edit_text)).getText().toString();
Здесь не работает без даункаста

2019-03-18 07:38 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        {
Фигурка на пред строке

2019-03-18 07:38 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +        outState.putParcelableArrayList("notes", (ArrayList<? extends Parcelable>) notes);
ключ notes в константы. Можно выделить "notes" и нажать CMD+ALT+C студия сама вынесет, и не забудь заменить на константу в другом месте где этот ключ юзается

2019-03-18 07:38 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +
пустая строка после javadoc не нужна

2019-03-18 07:59 UTC, lenant approved these changes

2019-03-18 07:59 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +        final TextView nameView;
N

2019-03-18 07:59 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +    private List<Note> notes = new ArrayList<>();
N

2019-03-18 07:59 UTC, lenant commented on app/src/main/java/com/example/notes/MainActivity.java
> +    public static final String NOTE_LIST = "notes";
Лучше называть ключи так, чтобы было понятно, к чему они относятся, например, давать префикс state к тем, что за сохранение состояния: STATE_NOTE_LIST

2019-03-18 08:24 UTC, merged