Added sorting and filtration
Grehhov/notes pull request #3
Opened 2019-03-21 13:51 UTC by Grehhov

2019-03-21 15:51 UTC, lenant requested changes

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +public class BottomSheetFragment extends Fragment {
Лучше назвать по другому, ведь суть фрагмента не в том, что он BottomSheet. Более того, сам он не должен знать, что он BottomSheet - он должен просто работать как фрагмент. Его bottom sheet поведением должен управлять фрагмент, в котором он находится.

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +        BottomSheetBehavior behavior = BottomSheetBehavior.from(bottomSheet);
Эти вещи нужно вынести в родительский фрагмент

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +        final RecyclerView recyclerViewNotes = getParentFragment().getView().findViewById(R.id.notes_recycler);
Это тоже стоит вынести в родительский фрагмент. В целом, завязываться на то, какие есть вьюхи в другом фрагменте - практика не очень, стоит общаться через интерфейс, дергая методы. Но тут стоит все про bottom sheet behaviour унести родителю.

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +    BottomSheetBehavior.BottomSheetCallback getBottomSheetCallback() {
N (тут и далее N означает отсутсвие Nullable или NonNull)

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +    SearchView.OnQueryTextListener getQueryTextListener(@NonNull final SearchView searchView) {
N

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +    View.OnClickListener getSortButtonClickListener(@NonNull final Button button, @NonNull final Button otherButton,
N

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +        searchView.setQuery("", false);
При таком подходе при смене конфигурации слетает query. Так делать не стоит. Давай только при возвращении с экрана создания заметки, если успешно создали, сбрасывать.

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/BottomSheetFragment.java
> +        if (str.charAt(str.length() - 1) == '↓' || str.charAt(str.length() - 1) == '↑') {
`str.charAt(str.length() - 1)` стоит вынести в переменную. В студии в конце выражения можно написать `.var` - так студия автоматом вынесет в переменную и заменит места, где встречается такое же выражение.

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +        SimpleDateFormat formatForDateNow = new SimpleDateFormat("hh:mm dd.MM.yyyy", Locale.ROOT);
`new SimpleDateFormat("hh:mm dd.MM.yyyy", Locale.ROOT)` нет нужды создавать этот объект каждый раз - ведь он все время одинаковый. Вынеси его как поле класса и инициализируй прямо в поле. Вместо `Locale.ROOT` используй `Locale.getDefault()` чтобы применились правила локали, которая используется приложением.

2019-03-21 15:51 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +                (int)(SIZE_DIVIDER_NOTE_LIST * getResources().getDisplayMetrics().density)));
Такие значение не стоит держать константами в коде. Используй файл dimens и храни их там с типом dp. Тогда не надо будет домножать на density - это произойдет под капотом. Для получения используй `getResources().getDimensionPixelSize(R.dimen.your_key)`

2019-03-21 15:51 UTC, lenant commented on app/src/main/res/layout/fragment_bottom_sheet.xml
> +<?xml version="1.0" encoding="utf-8"?>
Вместе с фрагментом стоит переименовать и этот файл и id-шники в нем (на всякий случай: shift+f6 переименует и подставит новое значения во все места использования, и для id-шников и для названия самого файла).

2019-03-22 09:32 UTC, lenant requested changes

2019-03-22 09:32 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +        BottomSheetBehavior bottomSheetBehavior = BottomSheetBehavior.from(bottomSheet);
Мне кажется, эту часть надо утащить в onCreateView

2019-03-22 09:32 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +        if (needCleanSearch) {
А вот эту часть может можно оставить в onStart, но не надо отсюда искать вьюху во вложенном фрагменте и напрямую сеттить ее значение. Нужно, чтобы фрагмент (`OptionsFragment`) был самостоятелен и такой функционал инкапсулировал. Чтобы если ты в нем поменяешь ввод текста, его принцип или просто id-шник, тебе не пришлось его менять еще и в другом фрагменте. Сделай у фрагмента метод типа clearQuery и в нем уже сеть пустой текст.

2019-03-22 09:36 UTC, lenant requested changes

2019-03-22 09:36 UTC, lenant commented on app/src/main/res/layout/fragment_notes.xml
> +    <android.support.design.widget.CoordinatorLayout
FrameLayout

2019-03-22 12:17 UTC, lenant requested changes

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +        stateBottomSheetBehavior = getBottomSheetBehavior().getState();
Имеет ли смысл тут записывать что-то в это поле, если в методе `onSaveInstanceState` ты все равно получаешь его значение через `getBottomSheetBehavior().getState()`? Мне кажется, это поле вообще не нужно.

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +            stateBottomSheetBehavior = savedInstanceState.getInt(STATE_BOTTOM_SHEET_BEHAVIOR);
Это поле можно убрать и использовать savedInstanceState в onCreateView

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +            optionsFragment.clearQuery();
Как подсказывает студия, `optionsFragment` может быть `null`, стоит его явно проверить. Тоже самое строчкой ниже - `getBottomSheetBehavior()` ты сам пометил как nullable, так что стоит его проверять.

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/OptionsFragment.java
> +    public interface ListActionHandler {
Мне кажется, по гайдлайнам, внутренний интерфейс должен быть над полями.

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/OptionsFragment.java
> +        SearchView searchView = getView().findViewById(R.id.options_search);
Держи `searchView` полем - ты и так находишь его в `onCreateView`. В общем случае поиск вьюхи в иерархии вьюх не быстрая операция (от этого все эти паттерны с view holder). Так что когда можно закешить найденную вьюху, стоит это сделать.

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
>      public void onBindViewHolder(@NonNull NotesViewHolder holder, final int position) {
Тут студия подсказывает тебе, что не надо замыкать position в  clickListener - вместо этого замыкай holder и используй `holder.getAdapterPosition()` в `onClick`

2019-03-22 12:17 UTC, lenant commented on app/src/main/java/com/example/notes/NoteAdapter.java
> +    public void sortByAddDate(final boolean isAscending) {
Зачем паблик? И в след методе тоже

2019-03-22 12:21 UTC, lenant commented on app/src/main/java/com/example/notes/NotesFragment.java
> +            optionsFragment.clearQuery();
В принципе, везде, где есть `getBottomSheetBehavior()` нужно его результат проверять на null.

2019-03-22 12:28 UTC, Grehhov commented on app/src/main/java/com/example/notes/NotesFragment.java
> +        stateBottomSheetBehavior = getBottomSheetBehavior().getState();
`onSaveInstanceState` не срабатывает при переходе на страницу создания/редактирования, только при повороте экрана

2019-03-22 13:37 UTC, lenant approved these changes

2019-03-25 08:38 UTC, merged